"""Updated student_course

Revision ID: 2c733b8c3278
Revises: c833af4c1f55
Create Date: 2022-10-25 12:32:10.050288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c733b8c3278'
down_revision = 'c833af4c1f55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_course',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_id')
    )
    op.drop_index('ix_student_courses_id', table_name='student_courses')
    op.drop_table('student_courses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_courses',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='student_courses_course_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='student_courses_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='student_courses_pkey')
    )
    op.create_index('ix_student_courses_id', 'student_courses', ['id'], unique=False)
    op.drop_table('student_course')
    # ### end Alembic commands ###
